# Generated by Django 4.2.4 on 2025-01-21 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_min_loan', models.IntegerField()),
                ('bank_max_loan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_updated', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('LOAN', 'loan'), ('FUND', 'fund'), ('INSTALLMENTS', 'installments')], max_length=50)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('loan_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_application_created', models.DateTimeField(auto_now_add=True)),
                ('loan_application_updated', models.DateTimeField(auto_now=True)),
                ('loan_application_status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='pending', max_length=50)),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_created', models.DateTimeField(auto_now_add=True)),
                ('loan_updated', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.IntegerField()),
                ('loan_tenure', models.IntegerField()),
                ('loan_interest', models.FloatField()),
                ('loan_status', models.CharField(choices=[('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='ongoing', max_length=50)),
                ('loan_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundApplication',
            fields=[
                ('fund_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_application_created', models.DateTimeField(auto_now_add=True)),
                ('fund_application_updated', models.DateTimeField(auto_now=True)),
                ('fund_application_status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='pending', max_length=50)),
                ('fund_amount', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
